application:
  shared:
    attribute: This is shared to all micro services.

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

# To allow unrestricted access to /actuator/refresh for testing
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: refresh