server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        # git:// is the read-only, unauthenticated protocol
        git:
          uri: https://github.com/munnachauhan/spring-boot-cloud-microservices.git
          # If resources in subdirectory
          searchPaths: configurations